services:
  - type: web
    name: glorb
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: GLORB_MAX_DURATION
        value: 120
