import re
import unittest
from pathlib import Path

import numpy as np

import generate
import main


NEW_PRESETS = ("glass", "clockwork", "creature", "cat", "birds", "electricity", "cave")


class NewPresetTests(unittest.TestCase):
    def test_catalogs_and_routes_include_every_new_preset(self):
        server = Path("server.py").read_text(encoding="utf-8")
        template = Path("templates/index.html").read_text(encoding="utf-8")
        docs = Path("docs/index.html").read_text(encoding="utf-8")
        for preset in NEW_PRESETS:
            self.assertIn(preset, main.SOUND_PRESETS)
            self.assertIn(preset, main._PRESET_EVENTS)
            self.assertIn(preset, generate.MODES)
            self.assertIn(f'"{preset}":', server)
            self.assertIn(f'data-mode="{preset}"', template)
            self.assertIn(f'data-mode="{preset}"', docs)

    def test_web_catalog_matches_python_catalog(self):
        html = Path("templates/index.html").read_text(encoding="utf-8")
        preset_section = html[html.index('id="mode-pills"'):html.index('id="nature-row"')]
        web_presets = re.findall(r'data-mode="([^"]+)"', preset_section)
        self.assertEqual(web_presets, list(main.SOUND_PRESETS))

    def test_continuous_arp_and_groove_audio_is_valid(self):
        np.random.seed(7)
        for preset in NEW_PRESETS:
            renderers = (
                getattr(main, f"make_{preset}_sequence")(.15),
                main.make_arp_sequence(.15, preset=preset),
                main.make_groove_sequence(.15, preset=preset),
            )
            for audio in renderers:
                self.assertEqual(audio.shape, (int(.15 * main.SAMPLE_RATE), 2))
                self.assertTrue(np.isfinite(audio).all())
                peak = float(np.max(np.abs(audio)))
                self.assertGreater(peak, 0)
                self.assertLessEqual(peak, .989)

    def test_every_animal_event_family_is_valid(self):
        np.random.seed(11)
        for table in (main._CAT_SOUNDS, main._BIRD_SOUNDS):
            for name, renderer, _weight in table:
                with self.subTest(event=name):
                    audio = renderer()
                    self.assertEqual(audio.ndim, 2)
                    self.assertEqual(audio.shape[1], 2)
                    self.assertTrue(np.isfinite(audio).all())
                    self.assertGreater(float(np.max(np.abs(audio))), 0.05)
                    self.assertLessEqual(float(np.max(np.abs(audio))), 0.71)

    def test_birds_are_spectrally_higher_than_cat_vocals(self):
        def centroid(audio):
            mono = np.mean(audio, axis=1)
            spectrum = np.abs(np.fft.rfft(mono * np.hanning(len(mono))))
            frequencies = np.fft.rfftfreq(len(mono), 1 / main.SAMPLE_RATE)
            return float(np.sum(frequencies * spectrum) / (np.sum(spectrum) + 1e-12))

        np.random.seed(19)
        cat_centroids = [centroid(main._cat_meow()) for _ in range(5)]
        bird_centroids = [centroid(main._bird_peep()) for _ in range(5)]
        self.assertGreater(np.median(bird_centroids), np.median(cat_centroids) * 1.35)

    def test_freesound_metadata_uses_current_style(self):
        for preset in ("cat", "birds"):
            description = generate.build_description(preset)
            self.assertNotIn("Every sound", description)
            self.assertNotIn("Three global knobs", description)
            self.assertIn("Generated by GLORB", description)
            self.assertTrue(generate.build_title(preset).endswith(" by GLORB"))


if __name__ == "__main__":
    unittest.main()
